projectGroup=com.misterpemodder
projectName=ShulkerBoxTooltip
projectBaseVersion=5.2.12
projectDescription=Adds a display of shulker box contents
projectArchiveBaseName=shulkerboxtooltip

# Minecraft
mcVersion=1.21.8
mcVersionFull=1.21.8

# Mod Loaders
enabledPlatforms=fabric,forge,neoforge
fabricLoaderVersion=0.17.2
fabricApiVersion=0.134.0+1.21.8
forgeVersion=1.21.8-58.1.7
neoForgeVersion=21.8.47

# Dependencies
modMenuVersion=15.0.0
janksonVersion=1.2.3

# Maven Metadata
pomName=Shulker Box Tooltip
gitLink=MisterPeModder/ShulkerBoxTooltip

# Hosting Platforms
hostGameVersions=1.21.8
curseProjectId=315811
modrinthProjectId=2M01OLQq

# Misc
org.gradle.jvmargs=-Xmx3G
