projectGroup=com.misterpemodder
projectName=ShulkerBoxTooltip
projectBaseVersion=5.2.6
projectDescription=Adds a display of shulker box contents
projectArchiveBaseName=shulkerboxtooltip

# Minecraft
mcVersion=1.21.3
mcVersionFull=1.21.3

# Mod Loaders
enabledPlatforms=fabric,forge,neoforge
fabricLoaderVersion=0.16.9
fabricApiVersion=0.107.0+1.21.3
forgeVersion=1.21.3-53.0.7
neoForgeVersion=21.3.6-beta

# Dependencies
modMenuVersion=12.0.0-beta.1
janksonVersion=1.2.0

# Maven Metadata
pomName=Shulker Box Tooltip
gitLink=MisterPeModder/ShulkerBoxTooltip

# Hosting Platforms
hostGameVersions=1.21.3
curseProjectId=315811
modrinthProjectId=2M01OLQq

# Misc
org.gradle.jvmargs=-Xmx3G
