projectGroup=com.misterpemodder
projectName=ShulkerBoxTooltip
projectBaseVersion=5.2.7-SNAPSHOT
projectDescription=Adds a display of shulker box contents
projectArchiveBaseName=shulkerboxtooltip

# Minecraft
mcVersion=1.21.6
mcVersionFull=1.21.6

# Mod Loaders
#enabledPlatforms=fabric,forge,neoforge
enabledPlatforms=fabric,neoforge
fabricLoaderVersion=0.16.14
fabricApiVersion=0.127.0+1.21.6
forgeVersion=1.21.5-55.0.3
neoForgeVersion=21.6.6-beta

# Dependencies
modMenuVersion=15.0.0-beta.1
janksonVersion=1.2.3

# Maven Metadata
pomName=Shulker Box Tooltip
gitLink=MisterPeModder/ShulkerBoxTooltip

# Hosting Platforms
hostGameVersions=1.21.5
curseProjectId=315811
modrinthProjectId=2M01OLQq

# Misc
org.gradle.jvmargs=-Xmx3G
