plugins {
    id 'com.gradleup.shadow' version '9.2.2'
}

def moduleArtifactId = "${rootProject.projectArchiveBaseName}-common"

base {
    archivesName = moduleArtifactId
}

architectury {
    common(rootProject.enabledPlatforms.split(','))
}

loom {
    accessWidenerPath = file('src/main/resources/shulkerboxtooltip.accesswidener')
}

configurations {
    shadowCommon
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    implementation "net.fabricmc:fabric-loader:${rootProject.fabricLoaderVersion}"

    // Nullable annotations.
    implementation 'com.google.code.findbugs:jsr305:3.0.2'
    implementation 'org.jetbrains:annotations:23.0.0'

    // Jankson
    compileOnly "blue.endless:jankson:${rootProject.janksonVersion}"
    shadowCommon "blue.endless:jankson:${rootProject.janksonVersion}"
}

javadoc {
    exclude 'com/misterpemodder/shulkerboxtooltip/impl/**'
    exclude 'com/misterpemodder/shulkerboxtooltip/mixin/**'
    exclude 'com/misterpemodder/shulkerboxtooltip/*.java'
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    archiveClassifier.set('javadoc')
    from javadoc.destinationDir
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    relocate 'blue.endless.jankson', "${rootProject.group}.shulkerboxtooltip.shadowed.blue.endless.jankson"

    configurations = [project.configurations.shadowCommon]
}

jar {
    archiveClassifier = 'raw'
}

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            groupId = project.group
            artifactId = moduleArtifactId
            version = project.version

            artifact(shadowJar) {
                builtBy shadowJar
            }

            artifact(sourcesJar) {
                builtBy sourcesJar
            }

            pom rootProject.ext.makePom(project)
        }
    }
}

signing {
    def signingKey = findProperty('signingKey')
    def signingPassword = findProperty('signingPassword')
    if (signingKey && signingPassword) {
        useInMemoryPgpKeys(signingKey, signingPassword)
        sign publishing.publications.mavenCommon
    } else {
        println("${project.name}: skipping jar signing")
    }
}
